# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown

# Sass settings
# sass:
#   sass_dir: assets/sass
sass:
  add_charset: true
  style: :compressed
  load_paths:
    - _sass
    - node_modules/foundation-sites/scss

# Build settings
exclude:
  - package.json
  - readme.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - yarn.lock
# exclude:
  # - package.json
  # - README.md
  # - CNAME
  # - assets/sass

# Plugin settings
plugin_dir:
  - jekyll-feed
  - jekyll-sitemap
